# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    #gradle(task: "clean assembleRelease")
    #upload_to_play_store(apk: '../build/app/outputs/apk/release/app-release.apk', track: 'beta')
    #upload_to_play_store(apk: '../build/app/outputs/apk/release/app-release.apk', track: 'internal')
    #upload_to_play_store(aab: '../build/app/outputs/bundle/release/app.aab', track: 'beta')
    # According to https://support.google.com/googleplay/android-developer/answer/3131213?hl=en
    # internal testing is quicker:
    # "When should I use an internal test?[...]Fast: You can distribute apps via the internal test track much faster than the open or closed tracks."
    upload_to_play_store(aab: '../build/app/outputs/bundle/release/app.aab', track: 'internal')
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
